services:

  postgres-shard-0:
    image: postgres:16-alpine
    container_name: TinyURL-Postgres-Shard-0
    restart: unless-stopped
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:       tinyURL_shard0
    ports:
      - "5434:5432"
    volumes:
      - pg_shard0_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tinyURL_shard0"]
      interval: 5s
      timeout:  3s
      retries:  5

  postgres-shard-1:
    image: postgres:16-alpine
    container_name: TinyURL-Postgres-Shard-1
    restart: unless-stopped
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:       tinyURL_shard1
    ports:
      - "5435:5432"
    volumes:
      - pg_shard1_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tinyURL_shard1"]
      interval: 5s
      timeout:  3s
      retries:  5

  redis:
    image: redis:7-alpine
    container_name: TinyURL-Redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: TinyURL-Prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: TinyURL-Grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

  k6:
    image: grafana/k6:latest
    container_name: TinyURL-k6
    profiles: ["tools"]
    volumes:
      - ../tests/load:/scripts
    environment:
      - TARGET_URL=http://host.docker.internal:3099
    command: run /scripts/k6_stress_test.js
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pg_shard0_data:
  pg_shard1_data:
  redis_data: